image:
  registry: docker.io
  repository: xebia/falco-eks-audit-bridge
  tag: v1.0.2
  pullPolicy: IfNotPresent
  replicas: 3
  namespace: falco

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

extraArgs: []
podSecurityPolicy: {}

rbac:
  create: true
  clusterRole:
    name: cr
  clusterRoleBinding:
    name: crb

serviceAccount:
  create: true
  name: feab

deployment:
  updateStrategy:
    type: RollingUpdate
  env: {}

proxy:
  httpProxy: "http://webproxy:3128"
  httpsProxy: "http://webproxy:3128"
  noProxy: ".plc,.local,localhost,169.254.169.254,169.254.170.2"

feab:
  service:
    enabled: true
    listenPort: 8080
    svcType: ClusterIP
    name: falco-feab-service
  bucket: 
  falco_ep: http://falco-audit-service.{{NAMESPACE}}.svc.cluster.local:8765/k8s-audit
  aws_region: eu-west-1

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
